version: "2"

services:
    gogs:
        image: gitea/gitea
        ports:
            - "10023:22"
        volumes:
            - ./gitea/:/data
        restart: on-failure:5
        networks:
         - traefik_net
         - default
        labels:
         - "traefik.enable=true"
         - "traefik.port=3000"
         - "traefik.docker.network=traefik_net"
         - "traefik.host.frontend.rule=Host:git.horst"
         - "traefik.url.frontend.rule=Host:git.srv.test.wiai.de"
    db:
        image: postgres:10-alpine
        volumes:
            - ./postgres/:/var/lib/postgresql/data
        env_file: postgres.env
        restart: on-failure:5

networks:
 traefik_net:
  external:
   name: traefik_net
