[web]
address = ":8080"

[docker]
domain = "lolnope.wiai.de"
watch = true
exposedbydefault = false


defaultEntryPoints = ["https", "http"]

[entryPoints]
	[entryPoints.http]
		address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
		address = ":443"
		[entryPoints.https.tls]


[acme]
	email = "tls-admin@example.org"
	storage = "acme.json"
	entryPoint = "https"
	OnHostRule = true
	[acme.httpChallenge]
		entryPoint = "http"
