version: "3"
services:
 traefik:
  image: traefik:1.5
  command: --configFile=/traefik.toml --logLevel="ERROR" --docker.domain="potato.kinf.wiai.uni-bamberg.de"
  volumes:
   - ./config.toml:/traefik.toml
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - 80:80
  networks:
   - net
  labels:
   - "traefik.enable=true"
   - "traefik.port=8080"
   - "traefik.frontend.rule=Host:traefik.localhost,traefik.potato.kinf.wiai.uni-bamberg.de"
networks:
 net:
  driver: bridge
