version: '2'
services:
 kibana:
  image: docker.elastic.co/kibana/kibana:6.2.1
  volumes:
   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  env_file: kibana.env
  networks:
   - default
   - traefik_net
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_net"
 elastic:
  image: docker.elastic.co/elasticsearch/elasticsearch-basic:6.2.1

networks:
 traefik_net:
  external:
   name: traefik_net
