version: "3"

services:
 web:
  build: ./docker2
  image: biogames:python2
  volumes:
   - ./biogames:/biogames
   - ../gamefield/:/gamefield
   - ./venv_web/:/venv/
   #- ./gg-data/files/:/biogames/files/
   #- ./gg-data/media/:/biogames/media/
  ports:
   - "5000:8000"
  restart: on-failure:5
  depends_on:
   - db

 celery:
  image: biogames:python2
  volumes:
   - ./biogames:/biogames
   - ./venv_celery/:/venv/
  restart: on-failure:5
  command: ["celery", "worker"]
  depends_on:
   - db

 db:
  image: mdillon/postgis
  volumes:
   - ./postgres/:/var/lib/postgresql/data
  environment:
   - POSTGRES_PASSWORD=secret
  restart: on-failure:5
