version: "3"

services:
    gogs:
        image: gogs/gogs
        ports:
            - "10022:22"
            - "10080:3000"
        volumes:
            - ./gogs/:/data
        restart: on-failure:5
    db:
        image: postgres:10-alpine
        volumes:
            - ./postgres/:/var/lib/postgresql/data
        env_file: postgres.env
        restart: on-failure:5
